### ISSUE TITLE
DMOnline, DMRole not working

### ISSUE THREAD

**Issue by sanderDijkxhoorn** [alexlyee/massdm#11]
DmAll works but role and online doesn't it will say: 

@mydiscord, An error occurred while running the command: ReferenceError: Permissions is not defined
You shouldn't ever receive an error like this.
Please contact mydiscord.

**Comment by alexlyee** [comment]
Please see other issues before posting yours, this is a known bug that has not been worked on. https://github.com/alexlyee/massdm/issues/3
