### ISSUE TITLE
It only sends messages to me and itself helpp

### ISSUE THREAD

**Issue by Mertcan213o** [alexlyee/massdm#12]
i just hop in a test server with 10 people and they are all online and i get this in console whats wrong?

Responding to mertcan :  Sending message to all 2 members of Test server.
(node:120) DeprecationWarning: Collection#filterArray: use Collection#filter instead
Waited 76ms.    |1|     DMing mertcan
Waited 112ms.   \/      DMing lol
Sent 2 messages successfully, 0 bots were skipped.
Unhandled promise rejection: DiscordAPIError: Cannot send messages to this user
    at C:\Users\Mertcan\Desktop\SADSA\node_modules\discord.js\src\client\rest\RequestHandlers\Sequential.js:79:15
    at C:\Users\Mertcan\Desktop\SADSA\node_modules\snekfetch\src\index.js:215:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  name: 'DiscordAPIError',
  message: 'Cannot send messages to this user',
  path: '/api/v7/users/555063767667310613/channels',
  code: 50007,
  method: 'POST'

**Comment by alexlyee** [comment]
It is highly likely that you incorrectly set up the bot, considering that it is only detecting two member in this test server of "10 people".
