### ISSUE TITLE
I can´t DM

### ISSUE THREAD

**Issue by ESPSERVERS** [alexlyee/massdm#18]
When I use the commands dmonline and dmrole an error appears:
An error occurred while running the command: ReferenceError: Permissions is not defined
You shouldn't ever receive an error like this.

What I have to do?
The bot has all the permissions on the server.

**Comment by alexlyee** [comment]
https://github.com/alexlyee/massdm/issues/3

Thank you for noting that dmrole does not work either. This is a known error. The bot must be fixed. If you would like to code it yourself and do a pull request I would happily credit you for your effort!
