### ISSUE TITLE
auto stooped

### ISSUE THREAD

**Issue by pikachu-bot-info** [alexlyee/massdm#30]
after dming 20 people the bot auto paused and says (press any key) after pressing key the start.bat file closed and bot goes offline can u please solve trhis iszsue thanks buddy for such awesome bot

**Comment by alexlyee** [comment]
Never heard of this issue before. Without more information there's no way I'm going to be able to solve it. Are you sure you aren't using the bot for a malicious purpose and you didn't set the delay between each message too low?
