### ISSUE TITLE
Error dmall

### ISSUE THREAD

**Issue by JvKiri** [alexlyee/massdm#4]
An error occurred while running the command: ReferenceError: Permissions is not defined

**Comment by Mahmudul-Hasan-Mahin** [comment]
i Gotted This Issue
Solve This

**Comment by alexlyee** [comment]
Use the github issues tab and please document your issue properly

**Comment by alexlyee** [comment]
More than likely you haven't set up the bot properly. I just deployed it myself without issues. Feel free to declare another issue if you still have this error, however next time please enter more information, especially including what you have done to set up the bot so far.
