### ISSUE TITLE
How to Send Private Message to Random People

### ISSUE THREAD

**Issue by royalus** [alexlyee/massdm#7]
i'd to ask if there any chance to send message to random people i mean to my friend list unless they're in my server like this pic. https://www.flickr.com/gp/183277075@N04/1Qk32D
sorry if i'm annoying

**Comment by alexlyee** [comment]
Like in that pic? Clearly annoying. Discord specifically is trying to counter bots that do this type of thing. My bot is built to overcome those automatic filters, but only in the context of **your** own server. Please do not attempt to use my code for something outside of it's intention: pinging a community one step further than @everyone.
